export const APP_CONFIG = {
  ATTENDANCE_STATUTORY_THRESHOLD: 75,
  MAX_FILE_SIZE_MB: 25,
  PAGINATION_LIMIT: 20,
  SUPPORTED_RESOURCE_TYPES: ['VIDEO', 'YOUTUBE', 'PDF', 'PRESENTATION', 'DOCUMENT', 'EXTERNAL_LINK'] as const
};
